name: Capture Commit Info

on:
  push:
    branches:
      - '**'  # on any branch push
jobs:
  list-branches-and-get-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history to get all branches

      - name: Fetch all branches
        run: git fetch --all

      - name: List branches with latest commit author email and date
        run: |
          echo "Branch | Commit Date | Author Email"
          echo "-------------------------------------"
          for branch in $(git branch -r | grep -v '\->'); do
            # trim origin/ prefix for nicer output
            branch_name=${branch#origin/}
            # get latest commit info on this branch
            commit_date=$(git log -1 --format="%cI" $branch)
            author_email=$(git log -1 --format="%ae" $branch)
            echo "$branch_name | $commit_date | $author_email"
          done
