name: Capture Commit Info

on:
  push:
    branches:
      - '**'  # on any branch push
jobs:
  list-branches-and-get-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: List branches with latest commit SHA, author email and date
        run: |
          echo "Branch | Commit SHA | Commit Date | Author Email"
          echo "-----------------------------------------------"
          for branch in $(git branch -r | grep -v '\->'); do
            branch_name=${branch#origin/}
            commit_sha=$(git log -1 --format="%H" $branch)
            commit_date=$(git log -1 --format="%cI" $branch)
            author_email=$(git log -1 --format="%ae" $branch)
            echo "$branch_name | $commit_sha | $commit_date | $author_email"
          done
