name: Clone Repository

on:
  push:
    branches:
      - poc/github_cloning
  workflow_dispatch:

jobs:
  clone-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory contents
        run: ls -la

      - name: Print current branch
        run: git branch

      - name: Show last commit
        run: git log -1

      - name: Print working directory
        run: pwd
