name: My First Workflow

on:
  push:
    branches:
      - github-test-poc
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"
